name: Build Validation

on:
  pull_request:
    branches: [ main ]  # or master
  push:
    branches: [ main ]  # or master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check for syntax errors
      run: node -c *.js
    
    - name: Create test .env file
      run: |
        echo "MONGODB_URI=mongodb://fake" >> .env
        echo "SESSION_SECRET=test" >> .env
        echo "GOOGLE_CLIENT_ID=fake" >> .env
        echo "GOOGLE_CLIENT_SECRET=fake" >> .env
        echo "REDIRECT_URL=http://localhost:3000/auth/gmail/callback" >> .env
        echo "PORT=3000" >> .env